### ISSUE TITLE
Add Chinese regions deaths

### ISSUE THREAD

**Issue by qleclerc** [eebrown/data2019nCoV#3]
Thank you for setting this up, this is an incredibly useful resource!

I was wondering if it would please be possible for you to also extract the reported deaths in Chinese regions, and include them in your dataset? These are currently presented in the WHO situation reports, but don’t appear in your dataset (only Chinese regions cases appear).

**Comment by eebrown** [comment]
When I have some time I'll go back and add these.

**Comment by qleclerc** [comment]
Thanks - I'll keep this ticket open in the meantime. Thank you for maintaining this in any case!

**Comment by eebrown** [comment]
The deaths data for Chinese provinces is now up (78a4843677e6b5fb8e0522e66e2a16c2edf4deb8). Thanks for the suggestions.

**Comment by qleclerc** [comment]
Many thanks!
