### ISSUE TITLE
Trailing spaces in WHO_SR.csv headings

### ISSUE THREAD

**Issue by ashleedawg** [eebrown/data2019nCoV#4]
(Great data source, thank you - the more people we have analyzing this data, the sooner a global solution will be found!)

_Tiny issue:_

**Country names and other headings in [WHO_SR.csv](https://github.com/eebrown/data2019nCoV/blob/master/data-raw/WHO_SR.csv) are sporadically padded with extra trailing spaces.** 

Examples: `"Nepal "` and `"UnitedStatesofAmerica "`

Could be an issue for those who don't realize a trim is necessary (ie., lookups via Excel; DB matching, etc)

**Comment by eebrown** [comment]
Thanks, good catch. Fixed it with commit 549ad6ae8f934ce282a2e3d57bbaf83003686988. 
Let me know if you find anything else.
