### ISSUE TITLE
'fansi' package error

### ISSUE THREAD

**Issue by air747** [eebrown/data2019nCoV#5]
I receive the following error:

_package ‘fansi’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version_

I mention that I tried all R versions from 3.6.0 to 3.6.3 (Ubuntu 18.04).

Please, can you provide the solution for this error?

**Comment by eebrown** [comment]
Hi, thanks for your comment. I think what has happened is that you upgraded R from the default version on Ubuntu 18.04 (which is 3.4.4) to R 3.6, but the version of the package `fansi` that you have installed is not compatible with 3.6. 
I have just lowered the required R version to 3.4 and confirmed that it installs on Ubuntu 18.04. I suggest you try installing the package with R 3.4.4 using `devtools::install_github("eebrown/data2019nCoV")`. Alternatively you could try updating/reinstalling your `fansi` package on 3.6 to see if that fixes the issue.

**Comment by air747** [comment]
Thank you for your help! 
I'm a new comer. 
Now the package it's installed:

_** testing if installed package can be loaded
* DONE (data2019nCoV)_

I load - library(data2019nCoV).

Open - data2019nCoV::WHO_SR and sarscov2_who_2019.

There is another way to open it, e.g. html or .csv file?

**Comment by eebrown** [comment]
Once installed, you load the package (like any other) with the command `library(data2019nCov)`. Then you have access to the data in an object called `WHO_SR`. You can see the vignette for examples on how to plot the data (https://htmlpreview.github.io/?https://github.com/eebrown/data2019nCoV/blob/master/doc/WHO_SR.html).

If you are new to R, there are many courses online. Here's a free popular textbook: https://r4ds.had.co.nz

**Comment by air747** [comment]
Let me appreciate your work and thank you for your support!

All the best!
